const actionTypes = {
    USER_CONNECTED: 'USER_CONNECTED',
    USER_DISCONNECTED: 'USER_DISCONNECTED',
    NEW_MESSAGE: 'NEW_MESSAGE',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_ERROR: 'AUTH_ERROR',
    CURRENT_MESSAGE_CHANGE: 'CURRENT_MESSAGE_CHANGE',
    USER_TAGGED: 'USER_TAGGED',
    SEARCH_QUERY_CHANGED: 'SEARCH_QUERY_CHANGED',
    SERVER_CONNECTED: 'SERVER_CONNECTED',
    SERVER_CONNECTION_ERROR: 'SERVER_CONNECTION_ERROR',
}

export default actionTypes;